eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
      
turbine:
  aggregator:
    clusterConfig: DEMOZUUL
  appConfig: demozuul
