eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value:${server.port}}
    leaseRenewalIntervalInSeconds: 10
